// Exact Figma property names that contain emoji or arrows (generated from the published library)
export const P = {
  anAdirRespuesta: "Añadir Respuesta",
  anAdirFila: "Añadir fila",
  linkMaSEventos: "Link - Más eventos",
  todoElDiA: "Todo el día",
  showHelper: "ℹ️ Show Helper",
  nested1: "↪ 1",
  nested1stButton: "↪ 1st Button",
  nested2ndButton: "↪ 2nd Button",
  nestedAvatar: "↪ Avatar",
  nestedBlocked: "↪ Blocked",
  nestedCta: "↪ CTA",
  nestedCloseIcon: "↪ Close Icon",
  nestedContent: "↪ Content",
  nestedEventoTodoElDiA2: "↪ Evento-todo el día 2",
  nestedEventoTodoElDiA3: "↪ Evento-todo el día 3",
  nestedEventoTodoElDiA4: "↪ Evento-todo el día 4",
  nestedHeader: "↪ Header",
  nestedIcon1: "↪ Icon 1",
  nestedIcon2: "↪ Icon 2",
  nestedIcon3: "↪ Icon 3",
  nestedIcon4: "↪ Icon 4",
  nestedIconLeft: "↪ Icon Left",
  nestedIconRight: "↪ Icon Right",
  nestedIndicatorLocation: "↪ Indicator Location",
  nestedInsetIndicatorLocation: "↪ Inset Indicator Location",
  nestedLink: "↪ Link",
  nestedShowAuthor: "↪ Show Author",
  nestedShowBullets: "↪ Show Bullets",
  nestedShowCaption: "↪ Show Caption",
  nestedShowItems: "↪ Show Items",
  nestedShowLink: "↪ Show Link",
  nestedShowNumber: "↪ Show Number",
  nestedShowTagsRow: "↪ Show Tags Row",
  nestedShowText: "↪ Show Text",
  nestedShowIcon2: "↪ Show icon 2",
  nestedShowIcon3: "↪ Show icon 3",
  nestedShowIcon4: "↪ Show icon 4",
  nestedShowIcon5: "↪ Show icon 5",
  nestedSlot: "↪ Slot",
  nestedSubtitle: "↪ Subtitle",
  nestedTag: "↪ Tag",
  nestedThumbnailLocation: "↪ Thumbnail Location",
  nestedTitle: "↪ Title",
  deepShowButton: "↪↪ Show Button",
  deepShowLabel: "↪↪ Show Label",
  deepShowPaginator: "↪↪ Show Paginator",
  subFloatLabel: "↳ Float Label",
  subFloatLabelVariant: "↳ Float Label Variant",
  subHelperText: "↳ Helper Text",
  subLabelText: "↳ Label",
  subLeftIcon: "↳ Left Icon",
  subRightIcon: "↳ Right Icon",
  iftaLabel: "▭ Ifta Label",
  state: "⚙️ State",
  showClearIcon: "✖️ Show Clear Icon",
  invalid: "❌ Invalid",
  showRightIcon: "➡️ Show Right Icon",
  rounded: "⥰ Rounded",
  showLeftIcon: "⬅️ Show Left Icon",
  raised: "⬆️ Raised",
  variant: "🎲 Variant",
  floatLabel: "🏷️ Float Label",
  fieldShowLabel: "🏷️ Show Label",
  showText: "👁️ Show Text",
  ghost: "🔤 Ghost",
  text: "🔤 Text",
  outlined: "🔲 Outlined",
  disabled: "🚫 Disabled",
  filled: "🟦 Filled",
  size: "🤏 Size",
} as const
