/**
 * PrimeNG defaults of the inputs whose story documents none (`table.defaultValue`), taken from the class
 * field initializers of primeng 21.1. Only booleans and appearance enums, which the panel shows as chosen
 * while unset. Unset `variant` follows the global `inputVariant` (outlined) and unset Dialog `position` is centred. A default documented in the story wins; once the stories document these, this map can go.
 */
export const PRIMENG_DEFAULTS: Record<string, Record<string, unknown>> = {
  Button: { iconPos: 'left' },
  SpeedDial: { type: 'linear', direction: 'up', hideOnClickOutside: true, rotateAnimation: true },
  SplitButton: { iconPos: 'left' },
  AutoComplete: { variant: 'outlined', unique: true, showEmptyMessage: true },
  DatePicker: { variant: 'outlined', showOtherMonths: true, showOnFocus: true, hideOnDateTimeSelect: true, focusTrap: true },
  FileUpload: { mode: 'advanced', showUploadButton: true, showCancelButton: true },
  FloatLabel: { variant: 'over' },
  IconField: { iconPosition: 'left' },
  InputNumber: { variant: 'outlined', format: true, allowEmpty: true, useGrouping: true },
  Knob: { showValue: true },
  Listbox: { showToggleAll: true },
  MultiSelect: { variant: 'outlined', filter: true, showToggleAll: true, showHeader: true, tooltipPosition: 'right', display: 'comma', highlightOnSelect: true },
  Password: { variant: 'outlined', feedback: true },
  Select: { variant: 'outlined', tooltipPosition: 'right', autofocusFilter: true },
  SelectButton: { allowEmpty: true },
  Slider: { orientation: 'horizontal' },
  ToggleButton: { iconPos: 'left' },
  TreeSelect: { variant: 'outlined', display: 'comma', filterInputAutoFocus: true, propagateSelectionDown: true, propagateSelectionUp: true, resetFilterOnHide: true },
  CascadeSelect: { variant: 'outlined' },
  Checkbox: { variant: 'outlined' },
  InputOtp: { variant: 'outlined' },
  InputText: { variant: 'outlined' },
  RadioButton: { variant: 'outlined' },
  Textarea: { variant: 'outlined' },
  DataTable: {
    alwaysShowPaginator: true,
    paginatorPosition: 'bottom',
    showFirstLastIcon: true,
    showPageLinks: true,
    resetPageOnSort: true,
    showLoader: true,
    showInitialSortBadge: true,
  },
  DataView: { layout: 'list', paginatorPosition: 'bottom', alwaysShowPaginator: true, showFirstLastIcon: true, showPageLinks: true },
  OrderList: { controlsPosition: 'left' },
  Paginator: { alwaysShow: true, showFirstLastIcon: true, showPageLinks: true },
  PickList: { showSourceFilter: true, showTargetFilter: true, showSourceControls: true, showTargetControls: true },
  Timeline: { align: 'left', layout: 'vertical' },
  Tree: { propagateSelectionUp: true, propagateSelectionDown: true },
  TreeTable: { alwaysShowPaginator: true, paginatorPosition: 'bottom', showFirstLastIcon: true, showPageLinks: true, resetPageOnSort: true, showLoader: true },
  Divider: { layout: 'horizontal', type: 'solid' },
  Panel: { iconPos: 'end', showHeader: true },
  Splitter: { layout: 'horizontal' },
  ConfirmDialog: {
    acceptVisible: true,
    rejectVisible: true,
    closeOnEscape: true,
    blockScroll: true,
    closable: true,
    focusTrap: true,
    modal: true,
    position: 'center',
    draggable: true,
  },
  Dialog: { position: 'center', draggable: true, resizable: true, closeOnEscape: true, closable: true, showHeader: true, focusOnShow: true, keepInViewport: true, focusTrap: true },
  Drawer: { modal: true, dismissible: true, closeOnEscape: true },
  Popover: { dismissable: true, focusOnShow: true },
  Tooltip: { escape: true, autoHide: true, fitContent: true, hideOnEscape: true },
  Dock: { position: 'bottom' },
  MegaMenu: { orientation: 'horizontal' },
  Carousel: { orientation: 'horizontal', showIndicators: true, showNavigators: true },
  Galleria: {
    showThumbnailNavigators: true,
    shouldStopAutoplayByClick: true,
    showThumbnails: true,
    thumbnailsPosition: 'bottom',
    indicatorsPosition: 'bottom',
  },
  Avatar: { size: 'normal', shape: 'square' },
  AvatarGroup: { size: 'normal' },
  MeterGroup: { orientation: 'horizontal', labelPosition: 'end', labelOrientation: 'horizontal' },
  ProgressBar: { showValue: true },
};
