import type { DesignSystemId } from './model';

/** Icon (Phosphor name) and one-line summary of each component for the home and section pages, by story title. */
const META: Record<string, [icon: string, summary: string]> = {
  // Button
  Button: ['cursor-click', 'Acción principal con variantes, tamaños, iconos y estados.'],
  SpeedDial: ['plus-circle', 'Botón flotante que despliega acciones rápidas.'],
  SplitButton: ['split-horizontal', 'Acción por defecto con un menú de alternativas.'],
  // Form
  AutoComplete: ['magnifying-glass', 'Campo con sugerencias mientras se escribe.'],
  CascadeSelect: ['flow-arrow', 'Selección en niveles anidados.'],
  Checkbox: ['check-square', 'Casilla de selección simple o múltiple.'],
  ColorPicker: ['palette', 'Selector de color en línea o desplegable.'],
  DatePicker: ['calendar-dots', 'Fecha y hora con calendario.'],
  Editor: ['text-aa', 'Editor de texto enriquecido.'],
  FileUpload: ['upload-simple', 'Subida de ficheros con arrastrar y soltar.'],
  FloatLabel: ['cursor-text', 'Etiqueta que flota sobre el campo al escribir.'],
  IconField: ['selection-plus', 'Campo de texto con icono dentro.'],
  IftaLabel: ['text-indent', 'Etiqueta dentro del campo, encima del valor.'],
  InputGroup: ['brackets-curly', 'Campo con complementos a los lados.'],
  InputNumber: ['hash', 'Entrada numérica con formato y botones.'],
  InputOtp: ['password', 'Código de un solo uso, dígito a dígito.'],
  InputText: ['textbox', 'Campo de texto básico.'],
  Knob: ['circle-half', 'Control circular de valor.'],
  Listbox: ['list-checks', 'Lista de opciones seleccionables.'],
  MultiSelect: ['check-circle', 'Desplegable de selección múltiple.'],
  Password: ['lock-key', 'Contraseña con indicador de fortaleza.'],
  RadioButton: ['radio-button', 'Una opción entre varias.'],
  Rating: ['star', 'Valoración con estrellas.'],
  Select: ['caret-up-down', 'Desplegable de selección única.'],
  SelectButton: ['selection-foreground', 'Grupo de botones que actúa como selector.'],
  Slider: ['sliders-horizontal', 'Valor o rango deslizando.'],
  Textarea: ['article', 'Texto de varias líneas.'],
  ToggleButton: ['toggle-left', 'Botón con estado activado o no.'],
  ToggleSwitch: ['toggle-right', 'Interruptor de encendido y apagado.'],
  TreeSelect: ['tree-evergreen', 'Desplegable con opciones en árbol.'],
  // Data
  DataTable: ['table', 'Tabla con ordenación, selección, filtros y paginación.'],
  DataView: ['squares-four', 'Resultados en rejilla o lista con plantilla propia.'],
  OrderList: ['list-numbers', 'Lista que el usuario puede reordenar.'],
  OrganizationChart: ['tree-structure', 'Organigrama jerárquico de nodos.'],
  Paginator: ['caret-double-right', 'Navegación entre páginas de resultados.'],
  PickList: ['arrows-left-right', 'Mueve elementos entre dos listas.'],
  Timeline: ['clock-counter-clockwise', 'Secuencia cronológica de eventos.'],
  Tree: ['tree-view', 'Árbol jerárquico expandible con selección.'],
  TreeTable: ['rows', 'Tabla con filas jerárquicas expandibles.'],
  // Panel
  Accordion: ['caret-circle-down', 'Secciones plegables.'],
  Card: ['cards', 'Tarjeta de contenido con los tipos y tamaños del DS.'],
  Divider: ['minus', 'Separador horizontal o vertical.'],
  Fieldset: ['bounding-box', 'Agrupa campos bajo una leyenda plegable.'],
  Panel: ['square-half-bottom', 'Contenedor con cabecera y plegado.'],
  ScrollPanel: ['scroll', 'Área con scroll personalizado.'],
  Splitter: ['columns', 'Paneles redimensionables.'],
  Stepper: ['steps', 'Proceso guiado en pasos.'],
  Tabs: ['tabs', 'Contenido organizado en pestañas.'],
  Toolbar: ['toolbox', 'Barra de acciones agrupadas.'],
  // Overlay
  ConfirmDialog: ['seal-question', 'Diálogo modal de confirmación.'],
  ConfirmPopup: ['chat-centered-text', 'Confirmación junto al elemento que la lanza.'],
  Dialog: ['frame-corners', 'Ventana modal con contenido libre.'],
  Drawer: ['sidebar-simple', 'Panel lateral deslizante.'],
  Popover: ['chat-circle', 'Capa flotante anclada a un elemento.'],
  Tooltip: ['info', 'Ayuda contextual al pasar el ratón.'],
  // Menu
  Breadcrumb: ['signpost', 'Ruta de navegación jerárquica.'],
  ContextMenu: ['dots-three-vertical', 'Menú al hacer clic derecho.'],
  Dock: ['app-window', 'Barra de aplicaciones con efecto lupa.'],
  MegaMenu: ['grid-four', 'Menú amplio en columnas.'],
  Menu: ['list', 'Menú simple de acciones.'],
  Menubar: ['browser', 'Barra de menú horizontal.'],
  PanelMenu: ['list-dashes', 'Menú en paneles tipo acordeón.'],
  TieredMenu: ['list-bullets', 'Menú con submenús en cascada.'],
  // Messages
  Message: ['warning-circle', 'Mensaje en línea por nivel de gravedad.'],
  Toast: ['bell-simple', 'Notificación temporal superpuesta.'],
  // Media
  Carousel: ['slideshow', 'Carrusel de elementos con navegación.'],
  Galleria: ['images', 'Galería con miniaturas y pantalla completa.'],
  Image: ['image-square', 'Imagen con vista previa ampliada.'],
  ImageCompare: ['split-vertical', 'Compara dos imágenes con un deslizador.'],
  // Misc
  Avatar: ['user-circle', 'Imagen, iniciales o icono de usuario.'],
  AvatarGroup: ['users-three', 'Avatares agrupados y solapados.'],
  Badge: ['notification', 'Indicador numérico o de estado.'],
  BlockUI: ['prohibit', 'Bloquea un área mientras se procesa.'],
  ButtonChip: ['funnel', 'Chip de filtro activable.'],
  Chip: ['tag-simple', 'Elemento compacto con texto, icono o imagen.'],
  Inplace: ['pencil-simple', 'Contenido que se edita en el sitio.'],
  MeterGroup: ['chart-bar', 'Medidas agrupadas en una barra.'],
  OverlayBadge: ['seal', 'Badge superpuesto sobre otro elemento.'],
  ProgressBar: ['chart-bar-horizontal', 'Progreso de una tarea.'],
  ProgressSpinner: ['spinner', 'Indicador de carga circular.'],
  ScrollTop: ['arrow-line-up', 'Botón para volver arriba.'],
  Skeleton: ['rectangle', 'Marcador de posición mientras carga.'],
  Tag: ['tag', 'Etiqueta de estado o categoría.'],
  Terminal: ['terminal-window', 'Consola de comandos simulada.'],
  // Proeduca
  ActionButtons: ['hand-tap', 'Botones de acción del patrón Proeduca.'],
  Agenda: ['calendar', 'Agenda de eventos y clases.'],
  BottomBar: ['device-mobile', 'Barra inferior de acciones en móvil.'],
  BottomSheet: ['arrow-square-up', 'Hoja inferior deslizante en móvil.'],
  ChatIaMessage: ['robot', 'Mensaje del asistente de IA.'],
  ChatMessage: ['chats-circle', 'Mensaje de chat entre personas.'],
  DocumentType: ['file-text', 'Tipo de documento con su icono.'],
  HistoryItem: ['chat-teardrop-text', 'Conversación del historial del chat IA.'],
  InputChat: ['paper-plane-right', 'Caja de entrada del chat.'],
  InputLink: ['link', 'Campo para enlaces.'],
  InputPhone: ['phone', 'Teléfono con prefijo de país.'],
  InputRGPD: ['shield-check', 'Aceptación de la protección de datos.'],
  Navbar: ['navigation-arrow', 'Barra de navegación principal.'],
  Profile: ['user-list', 'Perfil de usuario.'],
  Question: ['question', 'Pregunta de evaluación.'],
  Sidebar: ['sidebar', 'Menú lateral de la aplicación.'],
  StepperMobile: ['number-circle-one', 'Pasos de un proceso en móvil.'],
  TapBar: ['hand-pointing', 'Barra de pestañas inferior en móvil.'],
  TaskCard: ['note', 'Tarjeta de tarea.'],
  TaskColumn: ['kanban', 'Columna de tareas por estado.'],
  Topbar: ['align-top', 'Barra superior de página.'],
};

/** Same for AEM Portales, by story title. */
const AEM_META: Record<string, [icon: string, summary: string]> = {
  Button: ['cursor-click', 'Primario, secundario, ghost y outlined en tres tamaños, con icono y peligro.'],
  'Download Button': ['file-arrow-down', 'Descarga de documentos con su tipo de archivo, solo o en grupo.'],
  'Floating Button': ['chat-circle-dots', 'Acción principal flotante de la página.'],
  Chip: ['tag-simple', 'Filtros y opciones que se activan al pulsarlos.'],
  Checkbox: ['check-square', 'Casillas de selección múltiple.'],
  'Radio Button': ['radio-button', 'Elección única entre varias opciones.'],
  Toggle: ['toggle-right', 'Interruptor de activado o desactivado.'],
  'Input Text': ['textbox', 'Campo de texto con etiqueta flotante y validación.'],
  'Text Area': ['text-align-left', 'Texto largo con contador de caracteres.'],
  Search: ['magnifying-glass', 'Buscador con sugerencias.'],
  Dropdown: ['caret-circle-down', 'Desplegable de opción única o múltiple.'],
  Filter: ['funnel', 'Filtros en píldora para listados.'],
  'Date Picker': ['calendar-blank', 'Fecha con calendario desplegable.'],
  Slider: ['sliders-horizontal', 'Valor numérico en un rango.'],
  'Progress Spinner': ['spinner-gap', 'Indicador de carga.'],
  Tag: ['tag', 'Etiqueta informativa con icono.'],
  'Tag Set': ['tag-chevron', 'Modalidad y categorías de un contenido.'],
  'Date Tag': ['calendar-check', 'Fecha de un evento con su modalidad.'],
  Notification: ['bell-ringing', 'Avisos de éxito, error, aviso e información.'],
  Ticker: ['ticket', 'Datos clave del programa bajo la cabecera.'],
  Accordion: ['rows', 'Preguntas y contenido plegable.'],
  Avatar: ['user-circle', 'Personas, solas o en grupo.'],
  Card: ['cards', 'Noticias, eventos y programas con imagen.'],
  'Data Table': ['table', 'Tablas de datos con cabecera y enlaces.'],
  List: ['list-bullets', 'Listas con viñetas, números o iconos.'],
  'Anchor Menu': ['list-dashes', 'Navegación por las secciones de la página.'],
  Breadcrumb: ['caret-double-right', 'Ruta de la página actual.'],
  Pagination: ['dots-three', 'Navegación entre páginas de resultados.'],
  Tabs: ['tabs', 'Contenido organizado en pestañas.'],
  Section: ['rows', 'Contenedor de los módulos con su cabecera común.'],
  'Navigation Header': ['navigation-arrow', 'Cabecera de los portales con megamenú.'],
  Hero: ['image-square', 'Cabecera de página de programa, noticia o evento.'],
  'Hero Home': ['house-line', 'Cabecera de la home con destacados en carrusel.'],
  Accelerator: ['lightning', 'Barra de accesos rápidos.'],
  'Key Data': ['chart-bar', 'Datos clave del programa.'],
  'Distribution Bar': ['magnifying-glass', 'Buscador de titulaciones con desplegables.'],
  Distributor: ['squares-four', 'Accesos a las secciones del portal.'],
  'Card Block': ['cards-three', 'Carrusel de cards de programa.'],
  Banner: ['megaphone', 'Llamadas a la acción de marca, contenido, imagen o contacto.'],
  'Content Block': ['article', 'Texto e imagen en columnas.'],
  'Image Gallery': ['images', 'Galería de imágenes.'],
  'Logo Gallery': ['buildings', 'Logos de entidades colaboradoras.'],
  'Featured Data': ['number-circle-one', 'Cifras destacadas.'],
  'Featured Text': ['seal-check', 'Texto destacado con logo y botón.'],
  'Filter Module': ['funnel', 'Filtros de un listado con lo seleccionado.'],
  'Comparison Block': ['columns', 'Comparativa de opciones en columnas.'],
  'List Block': ['list-bullets', 'Listado en columnas con viñetas.'],
  'Accordion Block': ['question', 'Preguntas frecuentes con acordeón.'],
  Testimonial: ['quotes', 'Carrusel de testimonios de estudiantes.'],
  Form: ['note-pencil', 'Solicitud de información con contacto.'],
  Modal: ['app-window', 'Diálogo sobre la página con contenido con scroll.'],
  'Share Banner': ['share-network', 'Compartir en redes y copiar enlace.'],
  'Sticky Button': ['hand-tap', 'Barra fija inferior en móvil.'],
  'Thank You': ['confetti', 'Agradecimiento tras enviar un formulario.'],
  Footer: ['rows-plus-bottom', 'Pie con contacto, enlaces y redes.'],
  Home: ['house', 'Home del portal con buscador, oferta, eventos y actualidad.'],
  'Ficha MBA': ['graduation-cap', 'Ficha de programa con formulario lateral, plan de estudios y claustro.'],
  'Ficha Grado Educación': ['student', 'Ficha de grado con menciones, banner de oposiciones y claustro.'],
  Facultad: ['buildings', 'Facultad con áreas, oferta, eventos, actualidad y claustro.'],
  'Área Estudio': ['books', 'Área de estudio con titulaciones destacadas, eventos y recursos.'],
  Revista: ['newspaper', 'Portada de la revista con artículos y agenda.'],
  'Revista Categoría': ['newspaper-clipping', 'Categoría de la revista con artículos, paginación y newsletter.'],
  Noticia: ['article', 'Noticia con entradilla, cuerpo, galería y formulario lateral.'],
  Actualidad: ['broadcast', 'Portada de actualidad con noticias, agenda y compromiso social.'],
  'Actualidad Categoría': ['list-dashes', 'Categoría de actualidad con rejilla de noticias y paginación.'],
  Distributiva: ['funnel', 'Oferta académica con filtros laterales y resultados.'],
  Eventos: ['calendar-dots', 'Listado de eventos con filtros, tipos y eventos pasados.'],
  'Evento Detalle': ['calendar-check', 'Detalle de evento con ponentes y formulario de inscripción.'],
  Profesores: ['chalkboard-teacher', 'Claustro con rectorado, expertos y buscador de profesores.'],
  'Profesor Detalle': ['identification-card', 'Ficha de profesor con formación, experiencia y estudios.'],
  'Opinión': ['chat-centered-text', 'Opiniones de estudiantes con vídeos e historias de éxito.'],
  'Opiniones Fichas': ['star', 'Opiniones y valoración de una titulación.'],
  Becas: ['hand-coins', 'Becas con logo, plazo y estado, preguntas y noticias.'],
  'Beca Detalle': ['seal-percent', 'Detalle de beca con requisitos, pasos y documentación.'],
  FAQs: ['question', 'Preguntas frecuentes por tema.'],
};

export interface ComponentMeta {
  /** Phosphor icon class. */
  icon: string;
  summary: string;
}

/** Components without an entry fall back to the section icon and no summary. */
export function componentMeta(title: string, fallbackIcon: string, ds: DesignSystemId = 'prime-one'): ComponentMeta {
  const meta = (ds === 'aem' ? AEM_META : META)[title];
  return meta ? { icon: `ph ph-${meta[0]}`, summary: meta[1] } : { icon: fallbackIcon, summary: '' };
}
